// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/characters": {
    params: {};
  };
  "/characters/:id": {
    params: {
      "id": string;
    };
  };
  "/internal": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/characters" | "/characters/:id" | "/internal";
  };
  "features/home/pages/home.tsx": {
    id: "features/home/pages/home";
    page: "/";
  };
  "features/rick-and-morty/pages/characters.tsx": {
    id: "features/rick-and-morty/pages/characters";
    page: "/characters";
  };
  "features/rick-and-morty/pages/character-detail.tsx": {
    id: "features/rick-and-morty/pages/character-detail";
    page: "/characters/:id";
  };
  "features/health/pages/internal.tsx": {
    id: "features/health/pages/internal";
    page: "/internal";
  };
};